name: 'account'

on:
  push:
    branches-ignore: [ stable ]
    paths:
      - 'AccountService/**'

  pull_request:
    branches-ignore: [ stable ]
    paths:
      - 'AccountService/**'

env:
  DB_NAME: test
  DB_USER: test
  DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  DATABASE_URL: mongodb://$DB_USER:$DB_ROOT_PASSWORD@localhost:27017/$DB_NAME

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: healthcheck/mongo
        env:
          MONGO_INITDB_DATABASE: $DB_NAME
          MONGO_INITDB_ROOT_USERNAME: $DB_USER
          MONGO_INITDB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json, mbstring, pdo, mongodb
        env:
          update: true

      - name: Setup Redis with zhulik/redis-action
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v3
        working-directory: ./AccountService
        with:
          command: validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        working-directory: ./AccountService
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        uses: php-actions/composer@v3
        working-directory: ./AccountService

      - name: Run coding standards checks
        run: make cs
        # run: ./AccountService/vendor/bin/phpstan analyse src --level 5

      - name: Run phpunit for AccountService
        uses: php-actions/phpunit@v8
        working-directory: ./AccountService
