name: 'transaction'

on:
  push:
    branches-ignore: [ stable ]
    paths:
      - 'TransactionService/**'

  pull_request:
    branches-ignore: [ stable ]
    paths:
      - 'TransactionService/**'

env:
  DATABASE_URL: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json, mbstring, pdo
          tools: composer, phpunit:8.5.8, phpstan
        env:
          update: true

      - name: Setup Redis with zhulik/redis-action
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'

      # - name: Validate composer.json and composer.lock
      #   uses: php-actions/composer@v3
      #   with:
      #     working_dir: ./TransactionService
      #     command: validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          working_dir: ./TransactionService
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        working-directory: ./TransactionService
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run phpstan
        run: ${{ github.workspace }}/TransactionService/vendor/bin/phpstan analyse src --level 5

      - name: Run phpunit for TransactionService
        uses: php-actions/phpunit@v8
        with:
          configuration: ./TransactionService/phpunit.xml
